token: "API_TOKEN"    # lichess OAuth2 Token
url: "https://lishogi.org/"  # lichess base URL

engine:                      # engine settings
  dir: "./engines/"          # dir containing engines, relative to this project
  name: "engine_name"   # binary name of the engine to use
  protocol: "usi"            # "usi"
  ponder: false              # not supported!
# engine_options:            # any custom command line params to pass to the engine
#   cpuct: 3.1
  uci_options:               # arbitrary USI options passed to the engine
    #Move Overhead: 100       # increase if your bot flags games too often
    Threads: 2               # max CPU threads the engine can use
    USI_Hash: 256                # max memory (in megabytes) the engine can allocate
#   go_commands:             # additional options to pass to the USI go command
#     nodes: 1               # Search so many nodes only.
#     depth: 5               # Search depth ply only.
#     movetime: 1000         # Integer. Search exactly movetime milliseconds.
  silence_stderr: false      # some engines (yes you, leela) are very noisy

abort_time: 20               # time to abort a game in seconds when there is no activity
fake_think_time: false       # artificially slow down the bot to pretend like it's thinking
move_overhead: 1000          # increase if your bot flags games too often

challenge:                   # incoming challenges
  concurrency: 1             # number of games to play simultaneously
  sort_by: "first"           # possible values: "best", "first"
  accept_bot: true           # accepts challenges coming from other bots
  max_increment: 180         # maximum amount of increment to accaept a challenge. the max is 180. set to 0 for no increment
  min_increment: 0           # minimum amount of increment to accept a challenge
  variants:                  # chess variants to accept
    - standard
  time_controls:             # time controls to accept
    - ultrabullet
    - bullet
    - blitz
    - rapid
    - classical
#   - correspondence
  modes:                     # game modes to accept
    - casual                 # unrated games
    - rated                  # rated games - must comment if the engine doesn't try to win